lang = "en"
host = "blog.uwe.app"

[[scripts.main]]
type = "module"
src = "/assets/scripts/main.js"

[dependencies]
"std::author" = "^1"
"std::blueprint::blog" = "^1.0.5"
"std::core" = "^5"
"std::feed" = "^2"
"std::syntax" = "^1"

"uwe::brand::main" = { version = "^1", apply = { styles = [ "**" ] }, path = "../../brand/main" }
"uwe::brand::syntax" = { version = "^1", apply = { styles = [ "**" ] }, path = "../../brand/syntax" }

[dependencies."std::search"]
#path = "../../plugins/std/search"
version = "~1"
apply = { styles = [ "**" ] }

#[[scripts.main]]
#src = "/assets/js/main-nomodule.js"
#nomodule = true

[build]
extend = ["html"]
#tls = false
#parallel = false

[page]
description = "Articles and news from the UWE team"
keywords = "News, Insights, Web Editor, Static, Website, Generator, Headless CMS"
authors = ["tmpfs"]

#[sitemap]
#entries = 10

#[robots."*"]
#allow = ["*"]

#[robots."googlebot"]
#allow = ["/"]
#disallow = ["/posts"]

[feed.posts]
title = "Blog Posts"
description = "News and articles about the Universal Web Editor"
favicon = "/assets/favicon.png"
target = "posts"
includes = ["/posts/**"]
excludes = ["/posts/[0-9]*/", "/posts/"]

[feed.posts.alternate]
includes = ["/", "/posts/**/*.html"]

[syntax]
theme = "Solarized (light)"

[transform.html]
strip-comments = true
toc = true
words = true

[search.posts]
index = "/assets/search.idx"
results = 10
includes = ["/posts/**"]
excludes = ["/posts/[0-9]*/"]

[minify.html]
profiles = ["debug", "release"]

[db.load.posts]
type = "toml"
provider = "pages"
from = "posts"
excludes = ["index.*"]

[db.load.posts.on.all]
key = "*"

[db.load.posts.on.tags]
key = "taxonomies.tags"

#[db.load.posts.on.folders]
#key = "taxonomies.folders"

[redirects]
"/posts/" = "/posts/1/"

[pages."index.md".query]
name = "posts"
index = "all"
include-docs = true
sort = "created"
desc = true
limit = 2

[pages."posts/index.md".query]
name = "posts"
index = "all"
include-docs = true
page = {size = 5}
sort = "created"
desc = true

[pages."tags/index.md".query]
name = "posts"
index = "tags"
include-docs = true
group = {path = "taxonomies.tags", expand = true}

[pages."tags/item.md"]
title = "Tag"

[pages."tags/item.md".query]
name = "posts"
index = "tags"
each = true
include-docs = true
group = {path = "taxonomies.tags", expand = true}

#[pages."folders/index.md".query]
#name = "posts"
#index = "folders"
#include-docs = true
#group = {path = "taxonomies.folders", expand = true}

#[pages."folders/item.md".query]
#name = "posts"
#index = "folders"
#each = true
#include-docs = true
#group = {path = "taxonomies.folders", expand = true}

[link]
catalog = "links.md"

[authors.tmpfs]
name = "Muji"
url = "https://tmpfs.org"

[authors.chrism]
name = "Chris"
url = "https://chrism.blog"

#[hook.readme]
#path = "cp"
#args = ["-f", "build/readme/README.md", "."]
#after = true
#profiles = ["readme"]

#[profile.readme]
#source = "readme"
#rewrite-index = false
#use-layout = false
#paths = ["README.md"]
#types = {md = {}}
#collate = false

[publish.aws]
region = "ap-southeast-1"
credentials = "uwe"

[publish.aws.environments.production]
bucket = "blog.uwe.app"
